### PR TITLE
Fixes #47.  Added code to work with the message envelope if it is pro…

### LINKED ISSUE #47: Handle new MessageEnvelope from Core Data or App Service
Events received directly from Core Data or new Application Services are wrapped in the MessageEnvelope struct. Currently the rules engine fails to de-serialize MessageEnvelope and reports the error as not supporting CBOR.

Handle of the MessageEnvelope is required if we want new Application Services to replace Export Distro and send the events to the Rules Engine.

### PR DESCRIPTION
**Pull request by jpwhitemn**
…vided or deal with no envelope Event as in the past releases

Signed-off-by: Jim White <jpwhite_mn@yahoo.com>

### CODE REVIEW

File: src/main/java/org/edgexfoundry/messaging/ZeroMQEventSubscriber.java [hunk 1]
```diff
@@ -58,37 +61,37 @@
...
 			while (!Thread.currentThread().isInterrupted()) {
-				if (exportClient) {
-					if (serializedJava) { // supporting legacy Java export distro that shipped Serialized eventString
-						exportString = subscriber.recvStr();
-						event = toEvent(exportString);
-					} else { // supporting new Go export distro that ships JSON
-						exportBytes = subscriber.recv();
-						event = toEvent(exportBytes);
+				msgEnvenlope = subscriber.recvStr();
+				if (!"events".equals(msgEnvenlope)) { // why is every other event "events"?
```
Comment (lenny-intel) [inline src/main/java/org/edgexfoundry/messaging/ZeroMQEventSubscriber.java]: When connected directly to Core Data the new messaging is sending multiple part messages [<topic>,<payload>],  if you are not handling multi part messages you will be receive the topic, "events", as a message. I think this logic works, just change the comment to state something like "skip the 'events' topic"

File: src/main/java/org/edgexfoundry/messaging/ZeroMQEventSubscriber.java [hunk 2]
```diff
@@ -58,37 +61,37 @@
...
-					event = toEvent(exportBytes);
-				}
-				if (event == null) {
-					logger.info("CBOR is unsupported in the rules engine at this time; message being ignored");
-				} else {
-					engine.execute(event);
-					logger.info("Event sent to rules engine for device id:  " + event.getDevice());
-				}
+				} else
+					logger.debug("Received 'events' string");
```
Comment (lenny-intel) [inline src/main/java/org/edgexfoundry/messaging/ZeroMQEventSubscriber.java]: Remove now that this is explained.

File: src/main/java/org/edgexfoundry/messaging/ZeroMQEventSubscriber.java [hunk 3]
```diff
@@ -132,29 +143,32 @@ public void setZeromqAddressPort(String zeromqAddressPort) {
...
+	private void processJsonEvent(JsonNode node) throws IOException {
+		logger.info("JSON event received");
+		Event event = toEvent(node.get("Payload").binaryValue());
+		logger.debug("Event: " + event);
+		executeOnEvent(event);
+	}
+	
+	private void processEvent(JsonNode node) throws IOException {
+		logger.info("Event received");
+		Event event = mapper.convertValue(node, Event.class);
```
Comment (lenny-intel) [inline src/main/java/org/edgexfoundry/messaging/ZeroMQEventSubscriber.java]: This will get called when message is sent from export-distro because it doesn't wrap the message back into the MessageEnvelope. The message can still be json or cbor encoded. Will this handle either?

Should export distro wrap it back into the Message Envelope for consistency?

File: src/main/java/org/edgexfoundry/messaging/ZeroMQEventSubscriber.java (hunk 1 above)
Comment (jpwhitemn) [reply src/main/java/org/edgexfoundry/messaging/ZeroMQEventSubscriber.java]: Ugh - didn't even think about multi-part Lenny.  Couldn't figure out why the "events" message kept coming in.  I have address the message as multipart in the updated PR.

File: src/main/java/org/edgexfoundry/messaging/ZeroMQEventSubscriber.java (hunk 2 above)
Comment (jpwhitemn) [reply src/main/java/org/edgexfoundry/messaging/ZeroMQEventSubscriber.java]: yep - gone along with the entire conditional now that I am addressing multipart correctly.

File: src/main/java/org/edgexfoundry/messaging/ZeroMQEventSubscriber.java (hunk 3 above)
Comment (jpwhitemn) [reply src/main/java/org/edgexfoundry/messaging/ZeroMQEventSubscriber.java]: I think the intent of our work was to change the rules engine and not the other services and change the rules engine to handle wrapped or unwrapped message whether CBOR or JSON.  So I added some extra logic to handle CBOR unwrapped coming through export distro.

File: src/main/java/org/edgexfoundry/messaging/ZeroMQEventSubscriber.java [hunk 4]
```diff
@@ -58,36 +64,47 @@
...
-						event = toEvent(exportString);
-					} else { // supporting new Go export distro that ships JSON
-						exportBytes = subscriber.recv();
-						event = toEvent(exportBytes);
+				zmsg = ZMsg.recvMsg(subscriber);
+				parts = new ZFrame[zmsg.size()];
+				zmsg.toArray(parts);
+				logger.debug("Message has " + parts.length + " parts.");
+
+				if (parts.length < 2) {// if the message is not a multi-part message as delivered by core data
```
Comment (lenny-intel) [inline src/main/java/org/edgexfoundry/messaging/ZeroMQEventSubscriber.java]: Actually the non multi-part messages will be coming from Export Distro. Core Data is using the new Message Bus and send the data with the "events" topic. So the comment just needs `core data` changed to `export distro`

Comment (jpwhitemn) [reply src/main/java/org/edgexfoundry/messaging/ZeroMQEventSubscriber.java]: updated accordingly

File: src/main/resources/application.properties [hunk 5]
```diff
@@ -47,7 +47,7 @@ export.client.registration.retry.attempts=100
 #logging levels (used to control log4j entries)
 logging.level.org.springframework=ERROR
 logging.level.org.apache=ERROR
-logging.level.org.edgexfoundry=INFO
+logging.level.org.edgexfoundry=DEBUG
```
Comment (tsconn23) [inline src/main/resources/application.properties]: LogLevel default is usually INFO. Is this change intended?

Comment (jpwhitemn) [reply src/main/resources/application.properties]: Nope -  another JW oops

**Comment by jpwhitemn** [comment]
recheck
